# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swachh Bharat Abhiyaan
email: ebsb@iiti.ac.in
description: > # this means to ignore newlines until "baseurl:"
  Rashtriya Avishkar Abhiyan is a unique concept developed by the Ministry of Human Resource Development
  that aims to inculcate a spirit of inquiry, creativity and love for Science and Mathematics in school children.

# url: "https://webpagetemplate.github.io/"
# baseurl: "sba"
include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
parse_block_html: true
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
